# .streamlit/config.toml

[theme]
# A professional blue for interactive elements.
primaryColor = "#4285F4"

# The base background color (will be mostly covered by the image).
backgroundColor = "#F0F2F6"

# The background for secondary elements, kept light.
secondaryBackgroundColor = "#FFFFFF"

# Dark, readable text color.
textColor = "#1F1F1F"

# The font family for the app.
font = "sans serif"
