# .streamlit/config.toml

[theme]
# Google's primary blue color.
primaryColor = "#4285F4"

# A clean, pure white background.
backgroundColor = "#FFFFFF"

# A very light grey for the sidebar to subtly separate it.
secondaryBackgroundColor = "#F5F5F5"

# A dark, readable text color.
textColor = "#212121"

# The standard font for web apps.
font = "sans serif"
