# .streamlit/config.toml

[theme]
# The primary color for interactive elements
primaryColor = "#4285F4"  # Official Google Blue

# The main background of the app
backgroundColor = "#FFFFFF" # Pure White for a clean look

# The background for the sidebar and other secondary elements
secondaryBackgroundColor = "#F0F2F6" # A very light, subtle gray

# The color for all text
textColor = "#333333" # A dark gray instead of pure black for a softer feel

# The font family for the app
font = "sans serif"
